// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_System.Models;

public partial class answer
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int ansid { get; set; }

    public int quesid { get; set; }

    public bool isCorrect { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string title { get; set; }

    [InverseProperty("ans")]
    public virtual ICollection<Student_answer> Student_answers { get; set; } = new List<Student_answer>();

    [ForeignKey("quesid")]
    [InverseProperty("answers")]
    public virtual Question_Bank ques { get; set; }

    public Boolean isActive { get; set; }

}