// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_System.Models;

public partial class Comment
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int intakeNo { get; set; }

    public int? stdid { get; set; }

    public int? crsid { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string grade { get; set; }

    [Column(TypeName = "text")]
    public string comments { get; set; }

    [ForeignKey("crsid")]
    [InverseProperty("Comments")]
    public virtual course crs { get; set; }

    [ForeignKey("stdid")]
    [InverseProperty("Comments")]
    public virtual Student std { get; set; }
}