// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_System.Models;

[PrimaryKey("crsid", "dept_id", "branch_id")]
[Table("course_dept")]
public partial class course_dept
{
    [Key]
    
    public int crsid { get; set; }

    [Key]
    public int dept_id { get; set; }

    [Key]
    public int insid { get; set; }

    [Key]
    public int branch_id { get; set; }

    [ForeignKey("branch_id")]
    [InverseProperty("course_depts")]
    public virtual Branch branch { get; set; }

    [ForeignKey("crsid")]
    [InverseProperty("course_depts")]
    public virtual course crs { get; set; }

    [ForeignKey("dept_id")]
    [InverseProperty("course_depts")]
    public virtual Department dept { get; set; }

    [ForeignKey("insid")]
    [InverseProperty("course_depts")]
    public virtual Instructor ins { get; set; }

    public Boolean isActive { get; set; }

}