// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_System.Models;

public partial class course
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int crsid { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string crsname { get; set; }

    public int? hours { get; set; }

    [InverseProperty("crs")]
    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    [InverseProperty("crs")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    [InverseProperty("crs")]
    public virtual ICollection<Question_Bank> Question_Banks { get; set; } = new List<Question_Bank>();

    [InverseProperty("crs")]
    public virtual ICollection<Student_course> Student_courses { get; set; } = new List<Student_course>();

    [InverseProperty("crs")]
    public virtual ICollection<Topic> Topics { get; set; } = new List<Topic>();

    [InverseProperty("crs")]
    public virtual ICollection<course_dept> course_depts { get; set; } = new List<course_dept>();

    public Boolean isActive { get; set; }

}