// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Examination_System.Model.Models;
using Microsoft.EntityFrameworkCore;

namespace Examination_System.Models;


[Table("Department")]
[Index(nameof(name), IsUnique = true)]
public partial class Department
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int dept_id { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string name { get; set; }



    [InverseProperty("dept")]
    public virtual ICollection<User> Users { get; set; } = new List<User>();

    [InverseProperty("dept")]
    public virtual ICollection<course_dept> course_depts { get; set; } = new List<course_dept>();

    [InverseProperty("Department")]
    public virtual ICollection<Branch_Dept> Branch_Depts { get; set; } = new List<Branch_Dept>();
    public Boolean isActive { get; set; }

}