// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_System.Models;

[Table("Exam")]
public partial class Exam
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Exid { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string name { get; set; }

    public int? crsid { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? startat { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? endat { get; set; }

    public int? duration { get; set; }

    public int? insid { get; set; }

    public int deptid { get; set; }

    public int branchid {  get; set; }

    [ForeignKey("deptid")]
    public virtual Department department { get; set; }

    [ForeignKey("branchid")]
    public virtual Branch branch { get; set; }

    [InverseProperty("Exam")]
    public virtual ICollection<Student_Exam> Student_Exams { get; set; } = new List<Student_Exam>();

    [InverseProperty("exam")]
    public virtual ICollection<Student_answer> Student_answers { get; set; } = new List<Student_answer>();

    [ForeignKey("crsid")]
    [InverseProperty("Exams")]
    public virtual course crs { get; set; }

    [ForeignKey("insid")]
    [InverseProperty("Exams")]
    public virtual Instructor ins { get; set; }
    
    [ForeignKey("ExamId")]
    [InverseProperty("Exams")]
    public virtual ICollection<Question_Bank> QIDs { get; set; } = new List<Question_Bank>();

    public Boolean isActive { get; set; }

}