
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using Examination_System.Model.Models;
using Microsoft.EntityFrameworkCore;

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_System.Models;

[Table("Instructor")]
public partial class Instructor
{
    [Key]
    public int insid { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string jobTitle { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? salary { get; set; }

    [InverseProperty("Manager")]
    public virtual ICollection<Branch> ManagedBranches { get; set; } = new List<Branch>();

    [InverseProperty("ins")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    [InverseProperty("ins")]
    public virtual ICollection<Question_Bank> Question_Banks { get; set; } = new List<Question_Bank>();

    [InverseProperty("ins")]
    public virtual ICollection<course_dept> course_depts { get; set; } = new List<course_dept>();

    [ForeignKey("insid")]
    [InverseProperty("Instructor")]
    public virtual User ins { get; set; }

    [InverseProperty("Manager")]
    public virtual ICollection<Branch_Dept> ManagedDepartments { get; set; } = new List<Branch_Dept>();

    public Boolean isActive { get; set; }
}
