// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_System.Models;

[Table("Permission")]
public partial class Permission
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int PeriD { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string PerTitle { get; set; }

    [ForeignKey("PeriD")]
    [InverseProperty("Pers")]
    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();

    public Boolean isActive { get; set; }

}