// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_System.Models;

[Table("Question_Bank")]
public partial class Question_Bank
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int QID { get; set; }


    public int? insID { get; set; }
    public int? crsid { get; set; }

    public int? mark { get; set; }


    [StringLength(255)]
    [Unicode(false)]
    public string type { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string title { get; set; }

    [InverseProperty("qidNavigation")]
    public virtual ICollection<Student_answer> Student_answers { get; set; } = new List<Student_answer>();

    [InverseProperty("ques")]
    public virtual ICollection<answer> answers { get; set; } = new List<answer>();

    [ForeignKey("crsid")]
    [InverseProperty("Question_Banks")]
    public virtual course crs { get; set; }

    [ForeignKey("insID")]
    [InverseProperty("Question_Banks")]
    public virtual Instructor ins { get; set; }

    [ForeignKey("QID")]
    [InverseProperty("QIDs")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    public Boolean isActive {  get; set; }
}