// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_System.Models;

[Table("Student")]
public partial class Student
{
    [Key]
   
    public int stdid { get; set; }

    [InverseProperty("std")]
    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    [InverseProperty("std")]
    public virtual ICollection<Student_Exam> Student_Exams { get; set; } = new List<Student_Exam>();

    [InverseProperty("std")]
    public virtual ICollection<Student_answer> Student_answers { get; set; } = new List<Student_answer>();

    [InverseProperty("std")]
    public virtual ICollection<Student_course> Student_courses { get; set; } = new List<Student_course>();

    [ForeignKey("stdid")]
    [InverseProperty("Student")]
    public virtual User std { get; set; }
}