// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_System.Models;

[PrimaryKey("stdid", "ansid", "qid", "examId")]
[Table("Student_answer")]
public partial class Student_answer
{
    [Key]
  
    public int stdid { get; set; }

    [Key]
    public int ansid { get; set; }

    [Key]
    public int qid { get; set; }

    [Key]
    public int examId { get; set; }

    [ForeignKey("ansid")]
    [InverseProperty("Student_answers")]
    public virtual answer ans { get; set; }

    [ForeignKey("examId")]
    [InverseProperty("Student_answers")]
    public virtual Exam exam { get; set; }

    [ForeignKey("qid")]
    [InverseProperty("Student_answers")]
    public virtual Question_Bank qidNavigation { get; set; }

    [ForeignKey("stdid")]
    [InverseProperty("Student_answers")]
    public virtual Student std { get; set; }

    public Boolean isActive { get; set; }

}