// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_System.Models;

[PrimaryKey("stdid", "crsid")]
[Table("Student_course")]
public partial class Student_course
{
    [Key]
  
    public int stdid { get; set; }

    [Key]
    public int crsid { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string grade { get; set; }

    [Column(TypeName = "text")]
    public string comments { get; set; }

    [ForeignKey("crsid")]
    [InverseProperty("Student_courses")]
    public virtual course crs { get; set; }

    [ForeignKey("stdid")]
    [InverseProperty("Student_courses")]
    public virtual Student std { get; set; }

    public Boolean isActive { get; set; }

}