// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Examination_System.Models;

public partial class Topic
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int topicid { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string title { get; set; }

    public int? crsid { get; set; }

    [ForeignKey("crsid")]
    [InverseProperty("Topics")]
    public virtual course crs { get; set; }

    public Boolean isActive { get; set; }

}